stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - ng build

testing_testing:
  stage: test
  script: npm test