stages:
  - build
  - test

cache:
  paths:
    - node_modules/

testing_testing:
  stage: test
  script: 
    - npm install
    - ./node_modules/@angular/cli/bin/ng test --no-watch --no-progress --browsers=ChromeHeadlessCI