stages:
  - build
  - test

cache:
  paths:
    - node_modules/

Build:
  stage: build
  tags:
    - node
  script:
    - npm install

Test:
  stage: test
  script: 
    # Install Chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update 
    - apt-get install google-chrome-stable -y
    # Runs the tests.
      - npm run test:karma-headless
    - ./node_modules/@angular/cli/bin/ng test --no-watch --no-progress --browsers=ChromeHeadlessCI