image: node:latest
stages:
  - build
  - test

cache:
  paths:
    - node_modules/

#Build:
#  stage: build
#  script:
#    - npm install

Test:
  stage: test
  script: 
    - npm install
    - ./node_modules/@angular/cli/bin/ng test --watch=false --browsers=ChromeHeadless