variables:
  CLI_VERSION: 9.0.5

stages:
  - build
  - test

build:
 stage: build
 image: trion/ng-cli
 before_script:
  - npm ci
 script:
  - ng build --prod
 artifacts:
  expire_in: 1 day
  paths:
    - dist/
 tags:
   - docker
  only:
   - unit-tests

test:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  script:
   - ng test --progress false --watch false
  tags:
   - docker

test:e2e:
  stage: test
  image: trion/ng-cli-e2e:${CLI_VERSION}
  allow_failure: false
  script:
   - ng e2e
  tags:
   - docker