image:
stages:
  - build
  - test

cache:
  paths:
    - node_modules/

Build:
  stage: build
  tags:
    - node
  script:
    - npm install

Test:
  stage: test
  script: 
    - ng test --watch=false --browsers=ChromeHeadless