stages:
  - build
  - test

cache:
  paths:
    - node_modules/

 install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

Test:
  stage: test
  script: 
    - npm install
    - ./node_modules/@angular/cli/bin/ng test --watch=false --browsers=ChromeHeadless